room_booking_project/room_booking/urls.py
from django.conf import settings
from django.urls import path
from room_booking.views import *
from django.conf.urls.static import static

urlpatterns = [
    # Authentication
    path('signup/', signup_view, name='signup'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),

    # Room Views
    path('', room_list, name='room_list'),
    path('/<int:roomroom_id>/', room_details, name='room_details'),

    # Booking 
    path('book/<int:room_id>/', book_room, name='book_room'),
    path('booking/success/', booking_success, name='booking_success'),
    path('booking/history/', booking_history, name='booking_history'),

    # Payment
    path('payment/<int:room_id>/', payment_page, name='payment_page'),
    path('check-payment-status/<int:room_id>/', check_payment_status, name='check_payment_status'), 

    # Admin
    path('admin/dashboard/', admin_dashboard, name='admin_dashboard'),
    path('admin/statistics/', admin_statistics, name='admin_statistics'),
    path('admin/profile/', admin_profile, name='admin_profile'),
    path('admin/management/', admin_management, name='admin_management'), 
    path('admin/payment_slips/', admin_payment_slips, name='admin_payment_slips'),
    path('admin/payment_slips/<int:slip_id>/verify/', verify_payment_slip, name='verify_payment_slip'),
    path('admin/profile/<int:user_id>/', view_user, name='view_user'),
    path('admin/profile/<int:user_id>/edit/', edit_user, name='edit_user'),
    path('admin/profile/<int:user_id>/delete/', delete_user, name='delete_user'),
    path('book/<int:room_id>/', view_room, name='view_room'),
    path('admin/management/<int:room_id>/edit/', edit_room, name='edit_room'),
    path('admin/management/<int:room_id>/delete/', delete_room, name='delete_room'),
    path('admin/management/room/create/', create_room, name='create_room'),
    path('admin/profile/add_user/', add_user, name='add_user'),
    path('view_user/<int:user_id>/', view_user, name='view_user'),
    path('edit_user/<int:user_id>/', edit_user, name='edit_user'),
    path('delete_user/<int:user_id>/', delete_user, name='delete_user'),
    path('user_profile/<int:user_id>/', user_profile, name='user_profile'),
    path('api/room-booking-chart/', room_booking_chart_data, name='room_booking_chart_data'),
    # fetch data
    path('user-data/', user_data, name='user-data') 
    
] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

room_booking_project/room_booking_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include('room_booking.urls')),
    path("admin/", admin.site.urls),
]

room_booking_project/room_booking/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.core.exceptions import ValidationError
from django.utils import timezone
from django.contrib.auth import get_user_model

def get_default_username():
    return get_user_model().username

class Room(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='room_images/', null=True) # Define the image field
    beds = models.IntegerField()
    baths = models.IntegerField()
    size = models.IntegerField(help_text="Square footage of the room")
    rating = models.DecimalField(max_digits=3, decimal_places=1)
    reviews_count = models.IntegerField(default=0)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.name
    

class Booking(models.Model):
    booking_id = models.AutoField(primary_key=True)  
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    guest_name = models.CharField(max_length=255)
    checkin_date = models.DateField() 
    checkout_date = models.DateField()
    amount = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)  # New field for storing calculated amount

    def __str__(self):
        return f"Booking {self.booking_id} - {self.room.name} by {self.user.username}"

    def save(self, *args, **kwargs):
        if self.checkin_date and self.checkout_date and self.room:
            duration = (self.checkout_date - self.checkin_date).days
            if duration < 0:
                raise ValidationError("Checkout date must be after checkin date")

            self.amount = duration * self.room.price

        super().save(*args, **kwargs)
    
class PaymentSlip(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    slip = models.ImageField(upload_to='payment_slips/')
    verified = models.BooleanField(default=False)
    booking = models.ForeignKey(Booking, on_delete=models.CASCADE, null=True, blank=True)
    guest_name = models.CharField(max_length=255, default=get_default_username)
    booking_reference_id = models.IntegerField(default=0)
    checkin_date = models.DateField(default=timezone.now)
    checkout_date = models.DateField(default=timezone.now)

    def __str__(self):
        return f"Payment Slip for {self.room} by {self.user}"

room_booking_project/room_booking/views.py
from datetime import timedelta
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from .models import PaymentSlip, Room, Booking
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from .forms import BookingForm, PaymentForm, UserLoginForm, UserSignupForm
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test
import json
from django.http import JsonResponse
from django.contrib.auth.models import User
from .forms import UserForm
from .forms import RoomForm
from django.utils.timezone import datetime
from django.db.models import Sum, Count
import plotly.express as px
import plotly.io as pio
from django.shortcuts import render
from .models import Room
from django.db.models import Count
import plotly.express as px
import plotly.io as pio
from django.shortcuts import render
from .models import Room

def signup_view(request):
    if request.method == 'POST':
        form = UserSignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/')
    else:
        form = UserSignupForm()
    return render(request, 'room_booking/signup.html', {'form': form})

def login_view(request):
    form = UserLoginForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)

                # Redirect based on user type
                if user.is_staff:  # Assuming admins have is_staff flag set 
                    return redirect('admin_dashboard')  
                else:
                    return redirect('/')  
            else:
                pass
    return render(request, 'room_booking/login.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('/')

@login_required
def book_room(request, room_id):
    room = get_object_or_404(Room, id=room_id)
    if request.method == 'POST':
        form = BookingForm(request.POST)
        if form.is_valid():
            booking = form.save(commit=False)
            booking.user = request.user
            booking.room = room
            booking.save()  # Save booking without setting amount (it will be calculated automatically)
            return redirect('payment_page', room_id=room_id)
    else:
        form = BookingForm()
    return render(request, 'room_booking/book_room.html', {'room': room, 'form': form})

def booking_success(request):
    return render(request, 'room_booking/booking_success.html')

def room_list(request):
    rooms = Room.objects.all()
    return render(request, 'room_booking/room_list.html', {'rooms': rooms})

def room_details(request, room_id):
    room = get_object_or_404(Room, pk=room_id)
    return render(request, 'room_booking/room_details.html', {'room': room})

def user_profile(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    bookings = Booking.objects.filter(user=user)
    return render(request, 'room_booking/user_profile.html', {'user': user, 'bookings': bookings})

@login_required
def payment_page(request, room_id):
    room = get_object_or_404(Room, pk=room_id)

    if request.method == 'POST':
        form = PaymentForm(request.POST, request.FILES)
        if form.is_valid():
            uploaded_file = form.cleaned_data['slip']
            payment_amount = room.price

            # Retrieve the associated booking for the user and room
            booking = Booking.objects.filter(user=request.user, room=room).first()
            if booking:
                guest_name = booking.guest_name
                PaymentSlip.objects.create(
                    user=request.user,
                    room=room,
                    slip=uploaded_file,
                    verified=False,
                    booking=booking,  # Associate the PaymentSlip with the booking
                    guest_name=guest_name  # Include the guest name
                )
                countdown_end = timezone.now() + timedelta(minutes=10)
                request.session['countdown_end'] = countdown_end.isoformat()
                return render(request, 'room_booking/waiting_verification.html', {'room_id': room_id})
            else:
                messages.error(request, 'Booking not found.')
        else:
            messages.error(request, 'There was an error with your submission. Please check your data and try again.')
    else:
        form = PaymentForm()

    
    payment_amount = room.price
    context = {
        'form': form,
        'payment_amount': payment_amount,
        'bank_details': 'ABC Bank\nAccount Number: 123456789',
        'room_id': room_id,
    }
    return render(request, 'room_booking/payment_page.html', context)

@login_required
def booking_history(request):
    bookings = Booking.objects.filter(user=request.user)
    return render(request, 'room_booking/booking_history.html', {'bookings': bookings})

@user_passes_test(lambda u: u.is_superuser)
def admin_payment_slips(request):
    payment_slips = PaymentSlip.objects.filter(verified=False)
    return render(request, 'room_booking/admin_payment_slips.html', {'payment_slips': payment_slips})

def verify_payment_slip(request, slip_id):
    payment_slip = get_object_or_404(PaymentSlip, id=slip_id)
    payment_slip.verified = True
    payment_slip.save()
    messages.success(request, 'Payment slip verified successfully.')
    return redirect('admin_dashboard')

def check_payment_status(request, room_id):
    payment_slip = PaymentSlip.objects.filter(room_id=room_id, user=request.user).first()
    
    if payment_slip:
        return JsonResponse({'is_verified': payment_slip.verified})
    else:
        return JsonResponse({'error': 'Payment slip not found'}, status=404)

@user_passes_test(lambda u: u.is_staff)
def admin_dashboard(request):
    payment_slips = PaymentSlip.objects.all()  # Retrieve all payment slips
    return render(request, 'room_booking/admin_dashboard.html', {'payment_slips': payment_slips})

@user_passes_test(lambda u: u.is_staff) 
def admin_statistics(request):
    return render(request, 'room_booking/admin_statistics.html')

@user_passes_test(lambda u: u.is_staff) 
def admin_profile(request):
    users = User.objects.all()
    return render(request, 'room_booking/admin_profile.html', {'users': users})

@user_passes_test(lambda u: u.is_staff) 
def admin_management(request):
    rooms = Room.objects.all()
    return render(request, 'room_booking/admin_management.html', {'rooms': rooms})

def add_user(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('admin_profile')
    else:
        form = UserForm()
    return render(request, 'room_booking/add_user.html', {'form': form})

def view_user(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    return render(request, 'room_booking/view_user.html', {'user': user})

def edit_user(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    if request.method == 'POST':
        form = UserForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return redirect('admin_profile')
    else:
        form = UserForm(instance=user)
    return render(request, 'room_booking/edit_user.html', {'form': form})

def delete_user(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    user.delete()
    return redirect('admin_profile')

def view_room(request, room_id):
    room = get_object_or_404(Room, pk=room_id)
    return render(request, 'room_booking/view_room.html', {'room': room})

def edit_room(request, room_id):
    room = get_object_or_404(Room, pk=room_id)
    if request.method == 'POST':
        form = RoomForm(request.POST, instance=room)
        if form.is_valid():
            form.save()
            return redirect('admin_management')
    else:
        form = RoomForm(instance=room)
    return render(request, 'room_booking/edit_room.html', {'form': form})

def delete_room(request, room_id):
    room = get_object_or_404(Room, pk=room_id)
    if request.method == 'POST':
        room.delete()
        return redirect('admin_management')  # Or any other appropriate URL
    return render(request, 'room_booking/delete_room.html', {'room': room})

def create_room(request):
    if request.method == 'POST':
        form = RoomForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('admin_management')
    else:
        form = RoomForm()
    return render(request, 'room_booking/create_room.html', {'form': form})

def user_data(request):
    total_users = User.objects.count()
    users_with_bookings = Booking.objects.values_list('user', flat=True).distinct().count()

    user_list = User.objects.all().values('username', 'first_name', 'last_name')

    data = {
        'total_users': total_users,
        'users_with_bookings': users_with_bookings,
        'user_list': user_list
    }
    return JsonResponse(data)


def room_booking_chart(request):
    room_sizes = Room.objects.values('size').annotate(count=Count('id')).order_by('size')

    df = {
        "sizes": [r["id"] for r in room_sizes],
        "counts": [r["rating"] for r in room_sizes]
    }

    fig = px.bar(df, x="sizes", y="counts", title="Room Size Distribution")
    graph_html = pio.to_html(fig, full_html=False)

    return render(request, "room_booking/room_list.html", {"graph_html": graph_html})

def room_booking_chart_data(request):
    rooms = Room.objects.all()

    data = {

room_booking_project/room_booking/templates/room_booking/book_room.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Book Room - {{ room.name }}</title>
</head>
<style>
    body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
        background-color: #e0aeae;
    }

    .navbar {
        display: flex;
        justify-content: space-between;
        align-items: center;
        background-color: #ffffff;
        padding: 20px 20px;
        box-shadow: 0 2px 4px rgba(90, 90, 90, 0.1);
    }

    .navbar-item {
        margin-right: 15px;
        text-decoration: none;
        color: #333;
        font-weight: bold;
        transition: color 0.3s;
    }

    .navbar-item:hover {
        color: #003d82;
        /* Color changes on hover */
    }

    .navbar-logo,
    .navbar-item,
    .sign-up-btn {
        font-size: 18px;
    }

    .navbar-right {
        display: flex;
        justify-content: space-between;
        align-items: center;
        gap: 10px;
    }

    .login-btn {
        text-decoration: none;
        color: rgb(5, 5, 5);
        cursor: 16px;
        cursor: pointer;
        pointer-events: auto;
        padding: 9px 8px;
    }

    .sign-up-btn {
        text-decoration: none;
        color: #ffffff;
        padding: 9px 14px;
        background-color: #003d82;
        border-radius: 10px;
        cursor: 16px;
        cursor: pointer;
        pointer-events: auto;
        font-size: 16px;
        transition: background-color 0.3s;
    }

    .sign-up-btn:hover {
        background-color: #002c5e;
        ;
    }

    .content {
        display: flex;
        justify-content: center;
        align-items: flex-start;
        padding: 20px;
        gap: 20px;
        /* Adjust the space between columns */
    }

    .room-details {
        background-color: #ffffff;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        width: 35%;
        border: 1px solid rgb(194, 194, 194);
    }

    .img--cover img{
        width: 100%;
        height: auto;
        border-radius: 10px;
    }

    .booking-form {
        background-color: #fffbfb;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        width: 35%;
        border: 1px solid rgb(194, 194, 194);

    }

    .booking-form label {
        font-size: 18px;
        font-weight: 500;
    }

    .form-group {
        margin-bottom: 20px;
    }

    input {
        border: 1px solid rgb(194, 194, 194);
        padding: 5px;
        border-radius: 3px;
    }

    input[type="date"] {
        display: block;
        width: calc(100% - 20px);
        margin-right: 10px;
        margin-bottom: 10px;
    }

    
    .date-input {
        margin-bottom: 20px;
    
    }


    @media (max-width: 768px) {
        .content {
            flex-direction: column;
            align-items: center;
        }

        .room-details,
        .booking-form {
            width: 100%;
        }
    }

    button {
        margin-top: 50px;
        width: 100%;
        background-color: #217439;
        color: #ffffff;
        padding: 15px 0;
        font-size: 18px;
        font-weight: 600;
        border-radius: 5px;
        cursor: pointer;
        border: 1px solid rgb(194, 194, 194);
    }
</style>

<body>
    <nav class="navbar">
        <div class="navbar-left">
            <a href="{% url 'room_list' %}" class="navbar-item">BookingRooms</a>
        </div>
        <div class="navbar-right">
            {% if user.is_authenticated %}

            <a href="{% url 'user_profile' user.id %}" class="login-btn">{{ user.username }}</a>
            <a href="{% url 'logout' %}" class="sign-up-btn">Logout</a>

            {% else %}
            
            <a href="{% url 'login' %}" class="login-btn">Login</a>
            <a href="{% url 'signup' %}" class="sign-up-btn">Sign Up</a>

            {% endif %}
        </div>
    </nav>

    <div class="content">

        <div class="room-details">
            <div class="img--cover">
                <img src="{{ room.image.url }}" alt="{{ room.name }}" class="image">
            </div>
            <h1>Book Room - {{ room.name }}</h1>
            <p><strong>Beds:</strong> {{ room.beds }}</p>
            <p><strong>Baths:</strong> {{ room.baths }}</p>
            <p><strong>Size:</strong> {{ room.size }} Sq. Ft</p>
            <p><strong>Rating:</strong> {{ room.rating }} ({{ room.reviews_count }} reviews)</p>
            <p><strong>Price:</strong> ${{ room.price }}</p>
            <div class="description">
                <p><strong>Description:</strong>#########</p>
            </div>
        </div>

        <form method="post" class="booking-form">
            {% csrf_token %}
            <input type="hidden" name="room" value="{{ room.id }}">
            
            <div class="form-group">
                <label for="id_guest_name">Guest Name:</label>
                {{ form.guest_name }}
            </div>
            
            <div class="form-group date-input">
                <label for="id_checkin_date">Check-in Date:</label>
                {{ form.checkin_date }}
            </div>
            
            <div class="form-group date-input">
                <label for="id_checkout_date">Check-out Date:</label>
                {{ form.checkout_date }}
            </div>
            
            <button class="book-now" type="submit">Book Now</button>
        </form>
    </div>
</body>

</html>

room_booking_project/room_booking/templates/room_booking/delete_room.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Room</title>
</head>
<body>
    <h1>Confirm Delete Room</h1>
    <p>Are you sure you want to delete the room "{{ room.name }}"?</p>
    <form action="{% url 'delete_room' room.id %}" method="post">
        {% csrf_token %}
        <button type="submit">Confirm Delete</button>
    </form>
</body>
</html>

room_booking_project/room_booking/templates/room_booking/login.html
<!DOCTYPE html>
<html>

<head>
    <title>Login</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'room_booking/css/login.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/moment@2.29.4/moment.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<style media="screen">
    *,
    *:before,
    *:after {
        padding: 0;
        margin: 0;
        box-sizing: border-box;
    }

    body {
        background: #ffffff;
    }

    .background {
        width: 430px;
        height: 520px;
        position: absolute;
        transform: translate(-50%, -50%);
        left: 50%;
        top: 50%;
    }

    .background .shape {
        height: 200px;
        width: 200px;
        position: absolute;
        border-radius: 50%;
    }

    .shape:first-child {
        background: linear-gradient(#e66b07,
                #23a2f6);
        left: -80px;
        top: -80px;
    }

    .shape:last-child {
        background: linear-gradient(to right,
                #ff512f,
                #f09819);
        right: -30px;
        bottom: -80px;
    }

    form {
        height: 520px;
        width: 400px;
        background-color: rgba(219, 253, 246, 0.74);
        position: absolute;
        transform: translate(-50%, -50%);
        top: 50%;
        left: 50%;
        border-radius: 10px;
        backdrop-filter: blur(10px);
        border: 1px solid rgb(194, 194, 194);
        padding: 50px 35px;
    }

    form * {
        font-family: 'Poppins', sans-serif;
        color: #000000;
        letter-spacing: 0.5px;
        outline: none;
        border: none;
    }

    form h3 {
        font-size: 32px;
        font-weight: 600;
        line-height: 42px;
        text-align: center;
    }

    label {
        display: block;
        margin-top: 30px;
        font-size: 16px;
        font-weight: 500;
        color: #000000;
    }

    input {
        display: block;
        height: 50px;
        width: 100%;
        background-color: rgba(255, 255, 255, 0.07);
        border-radius: 3px;
        padding: 0 10px;
        margin-top: 8px;
        font-size: 14px;
        font-weight: 300;
        border: 1px solid rgb(194, 194, 194);
    }

    ::placeholder {
        color: #e5e5e5;
    }

    button {
        margin-top: 50px;
        width: 100%;
        background-color: #008250;
        color: #ffffff;
        padding: 15px 0;
        font-size: 18px;
        font-weight: 600;
        border-radius: 5px;
        cursor: pointer;
    }

</style>

<body>
    <form method="post" action="{% url 'login' %}" style="height: auto;">
        {% csrf_token %}
        <h3>Login</h3>

        {{ form.as_p }}

        <button type="submit" style="margin-top: 20px;">Log In</button>

        <div class="social">
        </div>

        <a href="{% url 'signup' %}" style="color: #000000; display: block; text-align: center; margin-top: 20px;">Sign up</a>
    </form>
</body>

</html>

room_booking_project/room_booking/templates/room_booking/payment_page.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Payment - {{ room.name }}</title>
    {% load static %}
</head>
<style>
    body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
        background-color: #ffffff;
    }

    .navbar {
        display: flex;
        justify-content: space-between;
        align-items: center;
        background-color: #ffffff;
        padding: 20px 20px;
        box-shadow: 0 2px 4px rgba(90, 90, 90, 0.1);
    }

    .navbar-item {
        margin-right: 15px;
        text-decoration: none;
        color: #333;
        font-weight: bold;
        transition: color 0.3s;
    }

    .navbar-item:hover {
        color: #003d82;
        /* Color changes on hover */
    }

    .navbar-logo,
    .navbar-item,
    .sign-up-btn {
        font-size: 18px;
    }

    .navbar-right {
        display: flex;
        justify-content: space-between;
        align-items: center;
        gap: 10px;
    }

    .login-btn {
        text-decoration: none;
        color: rgb(5, 5, 5);
        cursor: 16px;
        cursor: pointer;
        pointer-events: auto;
        padding: 9px 8px;
    }

    .sign-up-btn {
        text-decoration: none;
        color: #ffffff;
        padding: 9px 14px;
        background-color: #003d82;
        border-radius: 10px;
        cursor: 16px;
        cursor: pointer;
        pointer-events: auto;
        font-size: 16px;
        transition: background-color 0.3s;
    }

    .sign-up-btn:hover {
        background-color: #002c5e;
        ;
    }

    .content {
        display: flex;
        justify-content: center;
        align-items: flex-start;
        padding: 20px;
        gap: 20px;
        /* Adjust the space between columns */
    }

    .room-details {
        background-color: #fff;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        width: 35%;
        border: 1px solid rgb(194, 194, 194);
    }

    .img--cover img{
        width: 100%;
        height: auto;
        border-radius: 10px;
    }

    .booking-form {
        background-color: #fff;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        width: 35%;
        border: 1px solid rgb(194, 194, 194);

    }

    .booking-form label {
        font-size: 18px;
        font-weight: 500;
    }

    .form-group {
        margin-bottom: 20px;
    }

    input {
        border: 1px solid rgb(194, 194, 194);
        padding: 5px;
        border-radius: 3px;
    }

    input[type="date"] {
        display: block;
        width: calc(100% - 20px);
        margin-right: 10px;
        margin-bottom: 10px;
    }

    
    .date-input {
        margin-bottom: 20px;
    
    }


    @media (max-width: 768px) {
        .content {
            flex-direction: column;
            align-items: center;
        }

        .room-details,
        .booking-form {
            width: 100%;
        }
    }

    button {
        margin-top: 50px;
        width: 100%;
        background-color: #003d82;
        color: #ffffff;
        padding: 15px 0;
        font-size: 18px;
        font-weight: 600;
        border-radius: 5px;
        cursor: pointer;
        border: 1px solid rgb(194, 194, 194);
    }
</style>

<body>
    <nav class="navbar">
        <div class="navbar-left">
            <a href="{% url 'room_list' %}" class="navbar-item">BookingRooms</a>
        </div>
        <div class="navbar-right">
            {% if user.is_authenticated %}

            <a href="{% url 'user_profile' user.id %}" class="login-btn">{{ user.username }}</a>
            <a href="{% url 'logout' %}" class="sign-up-btn">Logout</a>

            {% else %}
            
            <a href="{% url 'login' %}" class="login-btn">Login</a>
            <a href="{% url 'signup' %}" class="sign-up-btn">Sign Up</a>

            {% endif %}
        </div>
    </nav>

    <div class="content">

        <div class="room-details">
            <div class="img--cover">
                <img src="{% static 'room_booking/assets/image/QR.png' %}" alt="QR Code" class="image">
            </div>
            <h1>Payment</h1>
            <p><strong>Amount : </strong> {{ payment_amount }}</p>
            <p><strong>Bank Details : </strong> {{ bank_details }}</p>
            <div class="description">
                
            </div>
        </div>

        <form method="post" class="booking-form" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="form-group">
                <label for="id_slip">Upload Slip:</label>
                {{ form.slip }}

            <button class="book-now" type="submit">Next</button>
        </form>
    </div>
</body>

</html>

room_booking_project/room_booking/templates/room_booking/view_payment_slip.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>View Payment Slip</title>
</head>
<body>
    <h1>View Payment Slip</h1>
    <p>User: {{ payment_slip.user.username }}</p>
    <p>Room: {{ payment_slip.room.location }}</p>
    <p>Slip Image:</p>
    <img src="{{ payment_slip.slip.url }}" alt="Payment Slip">
    <!-- Add more details as needed -->
</body>
</html>

room_booking_project/room_booking/templates/room_booking/view_room.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>View Room</title>
</head>
<body>
    <h1>Room Details</h1>
    <p>Name: {{ room.name }}</p>
    <p>Beds: {{ room.beds }}</p>
    <p>Baths: {{ room.baths }}</p>
    <p>Size: {{ room.size }}</p>
    <p>Rating: {{ room.rating }}</p>
    <p>Reviews Count: {{ room.reviews_count }}</p>
    <p>Price: {{ room.price }}</p>
    <img src="{{ room.image.url }}" alt="Room Image">
</body>
</html>